name: Publish NPM Package

on:
  push:
    tags:
      - "v*" # 当推送以v开头的标签（如v1.0.0）时触发
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 检出代码
      - uses: actions/setup-node@v4 # 设置Node.js环境
        with:
          node-version: 22 # 指定Node版本
          registry-url: "https://registry.npmjs.org/" # npm注册表地址

      - run: npm publish # 发布包
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 使用Secret中的Token
